Desktop version
NurkaAmre/portfolio-mobile-version pull request #6
Opened 2022-09-01 19:18 UTC by NurkaAmre

### Desktop version
- You need use @media query
- Setup size 1024px
- Be patience

2022-09-03 21:39 UTC, Ugboaja-Uchechi requested changes
Hi @NurkaAmre, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

- Linters are passing ✔️ 
- README is descriptive 👍 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-03 21:39 UTC, Ugboaja-Uchechi commented on style.css
> +  }
- [ ] Great job with your design 👍 . Kindly make sure your hero text is vertically centered as seen in the Figma design 🙏 

Figma Design | Your Design
------------- | -------------
![image](https://user-images.githubusercontent.com/74814780/188288301-28bdb1f2-f9fe-4bb2-b6bf-0bf418eaed59.png)  |  ![image](https://user-images.githubusercontent.com/74814780/188288289-d15a5c00-d24e-4cea-a0de-e946860fc870.png)

2022-09-03 21:39 UTC, Ugboaja-Uchechi commented on style.css
> +  }
- [ ] Kindly make sure you use the correct font size and weigh in the projects section 🙏 

Figma Design | Your Design
------------- | -------------
![image](https://user-images.githubusercontent.com/74814780/188288381-c6ec0579-040f-4a64-957b-a4a981c388ca.png)  |  ![image](https://user-images.githubusercontent.com/74814780/188288368-8646ecef-9203-4e41-a7fb-986f373686ba.png)

2022-09-03 21:39 UTC, Ugboaja-Uchechi commented on style.css
> +    padding-right: 70px;
- [ ] Kindly make sure you use the appropriate margin and spacing as seen in the Figma design 🙏 

Figma Design | Your Design
------------- | -------------
![image](https://user-images.githubusercontent.com/74814780/188288442-a414326c-5ad3-4eb4-84cc-105f3291f528.png)  |  ![image](https://user-images.githubusercontent.com/74814780/188288433-2cc7281e-f2e3-4b32-96da-4fc77ade390f.png)

2022-09-03 22:59 UTC, MahmoudBakr23 reviewed
# Hi @NurkaAmre  😃, 

As much as I appreciate your hard work on this project, I'm afraid that I can't perform a review on this pull request.

## **Invalid Submission**

- Please fix the Linters errors

_Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready._🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._

<hr>

_Invalid Code Review Request does not count into the code reviews limit._

2022-09-05 12:27 UTC, bellom commented
> ### Desktop version
> * You need use @media query
> * Setup size 1024px
> * Be patience

It would be nice to have a more descriptive PR description - you can list all the tasks you have done in the project requirement.

2022-09-05 12:28 UTC, bellom approved these changes
@NurkaAmre 

### This is a manual review

Note: It will be approved on your dashboard as soon as possible. 

# Approved

Cheers and Happy coding!👏👏👏

2022-09-05 19:08 UTC, merged